# Generated by Django 2.1.1 on 2018-10-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='original_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('i_data', models.DateTimeField()),
                ('o_data', models.DateTimeField()),
                ('i_total', models.BigIntegerField(verbose_name=20)),
                ('o_total', models.BigIntegerField(verbose_name=20)),
                ('amount', models.BigIntegerField(verbose_name=20)),
                ('time', models.IntegerField(verbose_name=11)),
                ('earn', models.BigIntegerField(verbose_name=20)),
                ('pct', models.FloatField()),
            ],
        ),
    ]
