# Generated by Django 2.1.1 on 2018-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalTradeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('operation', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'original_trade_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticTradeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('i_date', models.DateField(blank=True, null=True)),
                ('o_date', models.DateField(blank=True, null=True)),
                ('i_total', models.BigIntegerField(blank=True, null=True)),
                ('o_total', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('earning', models.BigIntegerField(blank=True, null=True)),
                ('pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistic_trade_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='original_trade',
        ),
    ]
