# Generated by Django 2.1.1 on 2018-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshare', '0002_auto_20181003_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='K_days',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'k_bfq',
                'managed': False,
            },
        ),
    ]
